version: '3.9'

services:
  product_services:
    build: 
      context: ./product_services
    working_dir: /app/
    volumes:
      - ./product_services:/app/ 
    ports:
      - 8000:8000 
    network_mode: bridge
    # networks:
      # - lara_react_dock_test
  
  web_frontend:    
    build: 
      context: ./web_frontend
    volumes:
      - ./web_frontend:/app/   
    ports:
      - 3000:3000    
    network_mode: bridge
  
  cache_service:
    image: redis:latest
    command: >
          --requirepass abcd1234
    ports:
      - 6379:6379
    network_mode: bridge

  no_sql_mongo:
    image: mongo:latest
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example  
    ports:
      - 27017:27017
    network_mode: bridge
    # networks:
      # - lara_react_dock_test 
# networks:
  # lara_react_dock_test:
  
    
